### ISSUE TITLE
Supported extensions to G729

### ISSUE THREAD

**Issue by JohannesLichtenberger** [BelledonneCommunications/bcg729#13]
Hello,

it seems G729 as well as G729 Annex B (VAD parameter) is at least supported by the bcg729 library. However, am I right, that Annex A and Annex J (G.729.1) are not supported?

kind regards
Johannes

**Comment by jeannotlapin** [comment]
Hi,
the supported variants are only the low complexity one: annex A and annex B. The other versions (including the main one) are not supported.

regards,
Johan
